<?php
// Unit tests for the dependency-free PDF writer (Employer/includes/pdf_writer.php).
// All offline: byte-string assertions on generated PDFs, no fonts to load,
// no network, no Firestore.

require_once __DIR__ . '/lib/assert.php';
pf_boot();
pf_header('pdf writer');

require_once __DIR__ . '/../Employer/includes/pdf_writer.php';

/* =========================================================
   Text safety
   ========================================================= */

pf_case('escaping');

assert_same('a\\(b\\)c\\\\d', pdf_safe_text('a(b)c\\d'), 'parens and backslash escaped');
assert_same('Jose', pdf_safe_text("Jos\xc3\xa9"), 'latin accent transliterated');
assert_same('Angeles Nunez', pdf_safe_text("Angeles N\xc3\xba\xc3\xb1ez"), 'tilde transliterated');
assert_same('plain ASCII untouched', pdf_safe_text('plain ASCII untouched'), 'ascii passthrough');
assert_same('AB???', pdf_safe_text("AB\xe4\xb8\xad"), 'non-latin bytes degrade to ? (one per byte)');
assert_same('a-b-c', pdf_safe_text("a\xc2\xb7b\xe2\x80\x93c"), 'middle dot and en dash map to hyphen');
assert_same('a-b', pdf_safe_text("a\xe2\x80\x94b"), 'em dash maps to hyphen');
assert_same('"q" \'s\'', pdf_safe_text("\xe2\x80\x9cq\xe2\x80\x9d \xe2\x80\x98s\xe2\x80\x99"), 'smart quotes straighten');
assert_same('wait...', pdf_safe_text("wait\xe2\x80\xa6"), 'ellipsis expands');
assert_same('A - B', pdf_safe_text('A • B'), 'bullet maps to hyphen');

pf_case('wrapping');

assert_same(['hello world'], pdf_wrap('hello world', 20), 'short line kept');
assert_true(count(pdf_wrap('one two three four five', 9)) > 1, 'long text wraps');
foreach (pdf_wrap('one two three four five', 9) as $line) {
    assert_true(strlen($line) <= 9, 'wrapped line within width');
}
assert_same(['abc', 'def'], pdf_wrap('abcdef', 3), 'long token hard-splits');

/* =========================================================
   Canonical fingerprint
   ========================================================= */

pf_case('fingerprint');

$docA = ['b' => 2, 'a' => ['y' => 1, 'x' => 0]];
$docB = ['a' => ['x' => 0, 'y' => 1], 'b' => 2];
assert_same(
    report_pdf_fingerprint($docA),
    report_pdf_fingerprint($docB),
    'key order independent'
);
assert_same(64, strlen(report_pdf_fingerprint($docA)), 'sha256 hex length');
assert_true(
    report_pdf_fingerprint(['a' => 1]) !== report_pdf_fingerprint(['a' => 2]),
    'content change alters fingerprint'
);

/* =========================================================
   PDF structure
   ========================================================= */

pf_case('document structure');

$pdf = report_pdf_build(
    'Monthly Performance Summary: Maria Santos',
    ['Maria Santos · Sep 2026 · Food Service'],
    [
        ['h', 'KPI Scores'],
        ['table', ['head' => ['KPI', 'Score', 'Target'], 'rows' => [
            ['Food Safety Compliance', '4.5', '4.5'],
            ['Service (open) Speed', '3.0', '4.0'],
        ]]],
        ['p', 'Average 3.8 / 5.0 across 4 rated KPIs.'],
        ['small', 'SHA-256: ' . str_repeat('a', 64)],
    ],
    'Generated by Performa'
);

assert_same('%PDF-1.4', substr($pdf, 0, 8), 'header');
assert_same('%%EOF', substr($pdf, -5), 'trailer end');
assert_contains('/Type /Catalog', $pdf, 'catalog present');
assert_contains('/BaseFont /Helvetica-Bold', $pdf, 'bold font present');
assert_contains('Monthly Performance Summary', $pdf, 'title embedded');
assert_contains('Food Safety Compliance', $pdf, 'table text embedded');
assert_contains('Service \\(open\\) Speed', $pdf, 'parens escaped in stream');
assert_contains('Page 1 of 1', $pdf, 'footer numbering');

// xref offsets must point at "N 0 obj" markers.
$xrefAt = strrpos($pdf, 'startxref');
assert_true($xrefAt !== false, 'startxref present');
$lines = explode("\n", $pdf);
$offsets = [];
$inXref = false;
foreach ($lines as $line) {
    if ($line === 'xref') {
        $inXref = true;
        continue;
    }
    if ($inXref) {
        if (preg_match('/^(\\d{10}) 00000 n $/', $line, $m)) {
            $offsets[] = (int) $m[1];
        } elseif (strpos($line, 'trailer') === 0) {
            break;
        }
    }
}
assert_true(count($offsets) > 3, 'xref lists objects');
$allPoint = true;
foreach ($offsets as $i => $off) {
    if (substr($pdf, $off, strlen(($i + 1) . ' 0 obj')) !== ($i + 1) . ' 0 obj') {
        $allPoint = false;
    }
}
assert_true($allPoint, 'every xref offset lands on its object header');

pf_case('multipage');

$manyRows = [];
for ($i = 1; $i <= 60; $i++) {
    $manyRows[] = ['KPI number ' . $i, '4.0', '4.0'];
}
$big = report_pdf_build('Big Report', ['meta line'], [
    ['table', ['head' => ['KPI', 'Score', 'Target'], 'rows' => $manyRows]],
], 'foot');
assert_contains('Page 2 of ', $big, 'long tables paginate');
assert_contains('KPI number 60', $big, 'last row survives pagination');

pf_case('multi-doc batch');

$batch = report_pdf_build_multi([
    ['title' => 'Cover', 'meta' => ['2 reports'], 'blocks' => [['p', 'Index.']], 'footer' => ''],
    ['title' => 'Report One', 'meta' => [], 'blocks' => [['p', 'Body one.']], 'footer' => ''],
    ['title' => 'Report Two', 'meta' => [], 'blocks' => [['p', 'Body two.']], 'footer' => ''],
]);
assert_contains('Report Two', $batch, 'batch contains all docs');
assert_contains('Page 3 of 3', $batch, 'batch paginates per document');

$eyebrowPdf = report_pdf_build('Jane Doe', ['Retail'], [['p', 'Body.']], '', 'Monthly Performance Summary');
assert_contains('MONTHLY PERFORMANCE SUMMARY', $eyebrowPdf, 'eyebrow renders uppercased');

pf_case('no diagnostics');

assert_no_php_warnings();

pf_summary();
