<?php
require_once __DIR__ . '/../auth.php';
require_once __DIR__ . '/../firebase_init.php';
require_login();
require_role('supervisor');

$supervisorName = $_SESSION['name'] ?? 'Supervisor';

$navItems = [
    ['label' => 'Dashboard', 'href' => 'supervisor_dashboard.php', 'active' => false],
    ['label' => 'My Employees', 'href' => 'employees.php', 'active' => false],
    ['label' => 'Rating Entry', 'href' => 'ratings.php', 'active' => false],
    ['label' => 'Reports', 'href' => 'reports.php', 'active' => true],
    ['label' => 'Settings', 'href' => 'settings.php', 'active' => false],
    ['label' => 'Notifications', 'href' => 'notifications.php', 'active' => false],
];

$reports = [];
try {
    $reportDocs = firestore_list_documents('Reports');
    usort($reportDocs, fn($a, $b) => strcmp($b['generatedAt'] ?? '', $a['generatedAt'] ?? ''));
    $reports = $reportDocs;
} catch (\Throwable $e) {
    // leave $reports empty if the collection doesn't exist yet
}
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Performa | Reports</title>
    <link rel="stylesheet" href="styles.css" />
</head>

<body>
    <div class="app-shell">
        <aside class="sidebar">
            <div>
                <div class="brand">
                    <div class="brand-mark">P</div>
                    <div>
                        <div class="brand-name">Performa</div>
                        <div class="brand-subtitle">Supervisor Dashboard</div>
                    </div>
                </div>
                <nav class="nav" aria-label="Primary">
                    <?php foreach ($navItems as $item): ?>
                        <a class="nav-item<?php echo $item['active'] ? ' active' : ''; ?>"
                            href="<?php echo htmlspecialchars($item['href'], ENT_QUOTES); ?>"><span><?php echo htmlspecialchars($item['label'], ENT_QUOTES); ?></span></a>
                    <?php endforeach; ?>
                </nav>
            </div>
            <div class="sidebar-footer">
                <div class="profile-avatar"><?php echo strtoupper(substr($supervisorName, 0, 2)); ?></div>
                <div>
                    <div class="profile-name"><?php echo htmlspecialchars($supervisorName, ENT_QUOTES); ?></div>
                    <div class="profile-role">Shift Supervisor</div>
                </div>
            </div>
        </aside>
        <main class="main">
            <section class="hero">
                <p class="eyebrow">Reports</p>
                <h1>View performance reports generated for your employees.</h1>
            </section>
            <section class="panel" style="padding:18px;">
                <div class="panel-header">
                    <div>
                        <h2>Generated Reports</h2>
                        <p>Live data from Firestore. Reports are generated by the Employer.</p>
                    </div>
                </div>

                <?php if (empty($reports)): ?>
                    <p style="padding:24px 0; color:var(--muted);">No reports have been generated yet.</p>
                <?php else: ?>
                    <div class="table-wrap" style="margin-top:14px;">
                        <div class="table-head"><span>Employee</span><span>Report Type</span><span>Industry</span><span>Generated</span>
                        </div>
                        <?php foreach ($reports as $r): ?>
                            <div class="table-row">
                                <div class="employee-cell">
                                    <div class="avatar"></div>
                                    <div>
                                        <div class="employee-name">
                                            <?php echo htmlspecialchars($r['employeeName'] ?? 'Unknown', ENT_QUOTES); ?>
                                        </div>
                                    </div>
                                </div>
                                <div class="timeline-cell">
                                    <div class="timeline-text">
                                        <?php echo htmlspecialchars($r['reportTypeLabel'] ?? 'Performance Report', ENT_QUOTES); ?>
                                    </div>
                                </div>
                                <div class="timeline-cell">
                                    <div class="timeline-text">
                                        <?php echo htmlspecialchars(ucfirst(str_replace('_', ' ', $r['industry'] ?? '')), ENT_QUOTES); ?>
                                    </div>
                                </div>
                                <div class="timeline-cell">
                                    <div class="timeline-text">
                                        <?php echo !empty($r['generatedAt']) ? date('M j, Y', strtotime($r['generatedAt'])) : '—'; ?>
                                    </div>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    </div>
                <?php endif; ?>
            </section>
        </main>
    </div>
    <script src="script.js"></script>
</body>

</html>